version: "3.7"
services:
  avatarlysis:
    build:
      context: .
      target: production
    container_name: avatarlysis-backend
    depends_on:
      - postgres
    env_file:
      - env.sh
    command: ["./main"]
    ports:
      - 8880:8880
    volumes:
      - ./avatarlysis:/avatarlysis
    tty: true
    networks:
      - backend

  postgres:
    image: postgres:12.2
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "avatars"
      POSTGRES_USER: "avatar"
      POSTGRES_PASSWORD: "av_s3cr37_!"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  pgdata:
  redisdata:
  avatarlysis:

networks:
  backend:
    driver: "bridge"
