version: "3.7"
services:
  avatarlysis:
    build:
      context: .
    container_name: avatarlysis-backend
    depends_on:
      - postgres
    env_file:
      - env.sh
    command:
      [
        "sh",
        "wait-for-it.sh",
        "postgres:5432",
        "--strict",
        "--timeout=300",
        "--",
        "sh",
        "run.sh",
      ]
    ports:
      - 8880:8880
    volumes:
      - ./avatarlysis:/avatarlysis
    tty: true
    networks:
      - backend

  postgres:
    image: postgres:12.2
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "avatars"
      POSTGRES_USER: "avatar"
      POSTGRES_PASSWORD: "av_s3cr37_!"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  pgdata:
  redisdata:
  fupisha:

networks:
  backend:
    driver: "bridge"